package io.github.absketches.runway.codegen;

import io.github.absketches.runway.codegen.sql.CodegenDialect;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RunwayGeneratorTest {
    private static final String PACKAGE_NAME = "io.github.absketches.runway.generated";
    private static final String CLASS_NAME = "GeneratedRunwayMigrations";

    @TempDir
    Path tempDir;

    @Test
    void generatesCompilableRegistry() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (name text default '\"\"\"');\r\n");
        Files.writeString(
            input.resolve("V2__create_user_view.sql"),
            "create view user_view as select name from users;\n"
        );

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        Path packageDirectory = packageDirectory(options);
        String catalog = Files.readString(packageDirectory.resolve(CLASS_NAME + ".java"));
        assertTrue(catalog.startsWith("// Generated by Runway. Do not edit."));
        assertTrue(catalog.contains("Migrations.builder(\"SQLite\", \""));
        assertTrue(catalog.contains("V1_CreateUsers.register(builder)"));
        assertTrue(catalog.contains("V2_CreateUserView.register(builder)"));

        String migration = Files.readString(packageDirectory.resolve("V1_CreateUsers.java"));
        assertTrue(migration.startsWith("// Generated by Runway. Do not edit."));
        assertTrue(migration.contains("sha256:"));
        assertTrue(migration.contains("builder.versioned("));
        assertTrue(migration.contains("\"V1__create_users.sql\""));
        assertTrue(migration.contains("List.of("));
        assertTrue(migration.contains("statement-000.sql"));
        assertTrue(!migration.contains("SqlImpact"));
        assertTrue(!migration.contains("create table users"));

        Path statement = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V1__create_users/statement-000.sql"
        );
        assertEquals("create table users (name text default '\"\"\"');\n", Files.readString(statement));

        String nativeMetadata = Files.readString(nativeMetadata(options));
        assertTrue(nativeMetadata.contains("\"typeReached\": \"" + PACKAGE_NAME + "." + CLASS_NAME + "\""));
        assertTrue(nativeMetadata.contains("\"glob\": \"io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/**\""));

        assertTrue(migration.contains("import io.github.absketches.runway.Migrations;"));
    }

    @Test
    void rejectsDuplicateVersions() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__first.sql"), "select 1;\n");
        Files.writeString(input.resolve("V1__second.sql"), "select 2;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));
        assertTrue(exception.getMessage().contains("Duplicate versioned migration version"));
    }

    @Test
    void allowsProceduresAndFunctionsAndMarksImpactIncomplete() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_display_name_function.sql"), """
            create function user_display_name(user_name varchar(255))
            returns varchar(255)
            deterministic
            return concat('user:', user_name);
            """);
        Files.writeString(input.resolve("V2__create_audit_procedure.sql"), """
            delimiter //
            create procedure runway_touch_audit_metadata()
            begin
              select 1;
            end//
            delimiter ;
            """);
        Path impactReport = tempDir.resolve("impact.html");

        CodegenOptions options = options(input, impactReport, CodegenDialect.MYSQL);
        new RunwayGenerator().generate(options);

        assertTrue(Files.exists(options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V1__create_display_name_function/statement-000.sql"
        )));
        assertTrue(Files.exists(options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V2__create_audit_procedure/statement-000.sql"
        )));

        String report = Files.readString(impactReport);
        assertTrue(report.contains("<input type=\"checkbox\" value=\"functions\"><span>functions</span>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"procedures\"><span>procedures</span>"));
        assertTrue(report.contains("functions.user_display_name"));
        assertTrue(report.contains("procedures.runway_touch_audit_metadata"));
        assertTrue(report.contains("<tr data-file-row data-file=\"V1__create_display_name_function.sql\" data-status=\"incomplete analysis\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V2__create_audit_procedure.sql\" data-status=\"incomplete analysis\""));
    }

    @Test
    void acceptsStatementsOutsideImpactAnalyzerCoverage() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__operations.sql"), """
            select * from users;
            truncate table audit_log;
            grant select on users to reporting;
            """);

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        Path resourceDirectory = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V1__operations"
        );
        assertTrue(Files.exists(resourceDirectory.resolve("statement-000.sql")));
        assertTrue(Files.exists(resourceDirectory.resolve("statement-001.sql")));
        assertTrue(Files.exists(resourceDirectory.resolve("statement-002.sql")));
    }

    @Test
    void readsAndWritesSqlAsUtf8() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        String sql = "insert into messages (content) values ('Grüße');\n";
        Files.writeString(input.resolve("V1__message.sql"), sql, StandardCharsets.UTF_8);
        Path impactReport = tempDir.resolve("impact.html");

        CodegenOptions options = options(input, impactReport);
        new RunwayGenerator().generate(options);

        Path statement = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V1__message/statement-000.sql"
        );
        assertEquals(sql, Files.readString(statement, StandardCharsets.UTF_8));
        String report = Files.readString(impactReport);
        assertTrue(report.contains("<!doctype html>"));
        assertTrue(report.contains("<input id=\"search\""));
        assertTrue(report.contains("<button id=\"copy-selection\" type=\"button\" disabled>Copy selected</button>"));
        assertTrue(report.contains("<button id=\"clear-selection\" type=\"button\" disabled>Clear selection</button>"));
        assertTrue(report.contains("copyColumns = ["));
        assertTrue(report.contains("[\"SQL file\", \"copyFile\"]"));
        assertTrue(report.contains("row.classList.toggle(\"selected\")"));
        assertTrue(report.contains("<h2>Migration Files</h2>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"messages\"><span>messages</span>"));
        assertTrue(report.contains("messages.content"));
        assertTrue(report.contains("<tr data-file-row data-file=\"V1__message.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("data-copy-file=\"V1__message.sql\""));
        assertTrue(report.contains("data-copy-runtime-writes=\"messages.content\""));
        assertTrue(report.contains("<span class=\"status data-change\">data changes</span>"));
        assertTrue(report.contains("<span class=\"chip data\" title=\"messages.content\">messages.content</span>"));
    }

    @Test
    void impactReportShowsSparseRowsAndConsolidationStatus() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__update_users.sql"), """
            update users u
            set status = r.default_status
            from roles r
            where u.role_id = r.id;
            """);
        Files.writeString(input.resolve("V2__rewrite_status.sql"), """
            update users
            set status = 'active';
            """);
        Files.writeString(input.resolve("V3__index_users_status.sql"), """
            create index users_status_idx
            on users (status);
            """);
        Files.writeString(input.resolve("V4__create_user_names_legacy.sql"), """
            create view user_names as
            select id
            from users;
            """);
        Files.writeString(input.resolve("V5__create_reporting_views.sql"), """
            create view user_ids as
            select id
            from users;

            create view role_names as
            select id
            from roles;
            """);
        Files.writeString(input.resolve("V6__replace_user_names.sql"), """
            drop view if exists user_names;

            create view user_names as
            select id, status
            from users;
            """);
        Files.writeString(input.resolve("V7__replace_user_ids.sql"), """
            drop view if exists user_ids;

            create view user_ids as
            select id, status
            from users;
            """);
        Files.writeString(input.resolve("V8__data_change_with_unknown.sql"), """
            update users
            set status = 'active';

            grant select on users to reporting;
            """);
        Files.writeString(input.resolve("V9__audit_user_status_changes.sql"), """
            create trigger users_status_audit
            after update of status on users
            begin
              insert into audit_log (event_name, severity)
              values (new.status, 'INFO');
            end;
            """);
        Path impactReport = tempDir.resolve("impact.html");

        new RunwayGenerator().generate(options(input, impactReport));

        String report = Files.readString(impactReport);
        assertTrue(report.contains("<h2>Migration Files</h2>"));
        assertTrue(report.contains("<span>Migration files</span>"));
        assertTrue(report.contains("<span>Schema points</span>"));
        assertTrue(report.contains("<label id=\"table-filter-label\">Tables</label>"));
        assertTrue(report.contains("<button class=\"filter-clear\" type=\"button\" data-clear-filter=\"table-filter\">Clear</button>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"users\"><span>users</span>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"roles\"><span>roles</span>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"indexes\"><span>indexes</span>"));
        assertTrue(report.contains("<input type=\"checkbox\" value=\"triggers\"><span>triggers</span>"));
        assertTrue(report.contains("clearCheckedValues(tableFilter)"));
        assertTrue(report.contains("writeClipboard(lines.join("));
        assertTrue(report.contains("indexes.users_status_idx"));
        assertTrue(report.contains("triggers.users_status_audit"));
        assertTrue(!report.contains("Table and Object Matrix"));
        assertTrue(report.contains("<tr data-file-row data-file=\"V9__audit_user_status_changes.sql\" data-status=\"active\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V3__index_users_status.sql\" data-status=\"active\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V2__rewrite_status.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V1__update_users.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V8__data_change_with_unknown.sql\" data-status=\"incomplete analysis\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V5__create_reporting_views.sql\" data-status=\"partial merge candidate\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V4__create_user_names_legacy.sql\" data-status=\"merge candidate\""));
        assertTrue(report.contains("<th>Runtime writes</th>"));
        assertTrue(report.contains("<th>Runtime reads</th>"));
        assertTrue(report.contains("<code>V7__replace_user_ids.sql</code>"));
        assertTrue(report.contains("<code>V6__replace_user_names.sql</code>"));
        assertTrue(report.contains("<span class=\"chip schema\" title=\"views.user_ids\">views.user_ids</span>"));
        assertTrue(report.contains("<span class=\"chip schema\" title=\"views.user_names\">views.user_names</span>"));
        assertTrue(report.contains("<span class=\"chip warning\" title=\"unknown\">unknown</span>"));
        assertTrue(report.contains("<summary>2 statements</summary>"));
    }

    @Test
    void analysisOnlyWritesImpactReportWithoutRuntimeCatalogOutput() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1.0__create-users.sql"), "create table users (id integer);\n");
        Files.writeString(input.resolve("V1_1__create-users.sql"), "create table users_archive (id integer);\n");
        Path impactReport = tempDir.resolve("impact.html");

        CodegenOptions options = analysisOnlyOptions(input, impactReport);
        new RunwayGenerator().generate(options);

        assertTrue(Files.exists(impactReport));
        assertTrue(Files.readString(impactReport).contains("Runway Impact Report"));
        assertTrue(Files.notExists(packageDirectory(options)));
        assertTrue(Files.notExists(options.resourceOutput()));
    }

    @Test
    void doesNotRejectUnsupportedKeywordsInsideCommentsOrStrings() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__keywords.sql"), """
            -- create function is documentation here
            insert into messages (content) values ('create trigger is plain text');
            """);

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        assertTrue(Files.exists(options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V1__keywords/statement-000.sql"
        )));
    }

    @Test
    void preservesOtherNativeImageMetadata() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");

        CodegenOptions options = options(input, null);
        Path existing = options.resourceOutput()
            .resolve("META-INF/native-image/example/other/reachability-metadata.json");
        Path existingPackageMetadata = options.resourceOutput()
            .resolve("META-INF/native-image")
            .resolve(PACKAGE_NAME.replace('.', '/'))
            .resolve(CLASS_NAME)
            .resolve("reachability-metadata.json");
        Files.createDirectories(existing.getParent());
        Files.createDirectories(existingPackageMetadata.getParent());
        Files.writeString(existing, "{\"reflection\":[]}\n");
        Files.writeString(existingPackageMetadata, "{\"resources\":[]}\n");

        new RunwayGenerator().generate(options);

        assertEquals("{\"reflection\":[]}\n", Files.readString(existing));
        assertEquals("{\"resources\":[]}\n", Files.readString(existingPackageMetadata));
        assertTrue(Files.exists(nativeMetadata(options)));
    }

    @Test
    void removesStaleGeneratedMigrationOutput() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Path obsolete = input.resolve("V2__obsolete.sql");
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");
        Files.writeString(obsolete, "create table obsolete (id integer);\n");

        CodegenOptions options = options(input, null);
        Path handwritten = packageDirectory(options).resolve("HandWritten.java");
        Files.createDirectories(handwritten.getParent());
        Files.writeString(handwritten, """
            package io.github.absketches.runway.generated;

            final class HandWritten {
            }
            """);
        new RunwayGenerator().generate(options);
        Path obsoleteSource = packageDirectory(options).resolve("V2_Obsolete.java");
        Path obsoleteResource = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/GeneratedRunwayMigrations/V2__obsolete/statement-000.sql"
        );
        assertTrue(Files.exists(obsoleteSource));
        assertTrue(Files.exists(obsoleteResource));

        Files.delete(obsolete);
        new RunwayGenerator().generate(options);

        assertTrue(Files.notExists(obsoleteSource));
        assertTrue(Files.notExists(obsoleteResource));
        assertTrue(Files.exists(handwritten));
    }

    @Test
    void doesNotRemoveOtherCatalogOutputInSamePackage() throws Exception {
        Path firstInput = tempDir.resolve("first-runway");
        Path secondInput = tempDir.resolve("second-runway");
        Files.createDirectories(firstInput);
        Files.createDirectories(secondInput);
        Files.writeString(firstInput.resolve("V1__create_users.sql"), "create table users (id integer);\n");
        Files.writeString(secondInput.resolve("V2__create_orders.sql"), "create table orders (id integer);\n");

        CodegenOptions first = options(firstInput, null);
        CodegenOptions second = options(secondInput, null, CodegenDialect.SQLITE, "OtherRunwayMigrations");
        new RunwayGenerator().generate(second);
        Path secondCatalog = packageDirectory(second).resolve("OtherRunwayMigrations.java");
        Path secondSource = packageDirectory(second).resolve("V2_CreateOrders.java");
        Path secondResource = second.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/OtherRunwayMigrations/V2__create_orders/statement-000.sql"
        );

        new RunwayGenerator().generate(first);

        assertTrue(Files.exists(secondCatalog));
        assertTrue(Files.exists(secondSource));
        assertTrue(Files.exists(secondResource));
    }

    @Test
    void refusesToOverwriteNonRunwayJavaSource() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");

        CodegenOptions options = options(input, null);
        Path catalog = packageDirectory(options).resolve(CLASS_NAME + ".java");
        Files.createDirectories(catalog.getParent());
        Files.writeString(catalog, """
            package io.github.absketches.runway.generated;

            final class GeneratedRunwayMigrations {
            }
            """);

        CodegenException exception = assertThrows(
            CodegenException.class,
            () -> new RunwayGenerator().generate(options)
        );

        assertTrue(exception.getMessage().contains("Refusing to overwrite non-Runway Java source"));
    }

    @Test
    void rejectsGeneratedClassNameCollisions() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1-1__create-users.sql"), "create view users_a as select id from users;\n");
        Files.writeString(input.resolve("V1_1__create users.sql"), "create view users_b as select id from users;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));

        assertTrue(exception.getMessage().contains("same Java class"));
    }

    @Test
    void rejectsRepeatableMigrationFilenames() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("R__refresh_users.sql"), "create view users_v as select id from users;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));

        assertTrue(exception.getMessage().contains("Invalid migration filename"));
    }

    private CodegenOptions options(Path input, Path impactReport) {
        return options(input, impactReport, CodegenDialect.SQLITE);
    }

    private CodegenOptions options(Path input, Path impactReport, CodegenDialect dialect) {
        return options(input, impactReport, dialect, CLASS_NAME);
    }

    private CodegenOptions options(Path input, Path impactReport, CodegenDialect dialect, String className) {
        return new CodegenOptions(
            input,
            tempDir.resolve("sources"),
            tempDir.resolve("resources"),
            PACKAGE_NAME,
            className,
            dialect,
            impactReport,
            false
        );
    }

    private CodegenOptions analysisOnlyOptions(Path input, Path impactReport) {
        return new CodegenOptions(
            input,
            tempDir.resolve("sources"),
            tempDir.resolve("resources"),
            PACKAGE_NAME,
            CLASS_NAME,
            CodegenDialect.SQLITE,
            impactReport,
            true
        );
    }

    private static Path packageDirectory(CodegenOptions options) {
        return options.sourceOutput().resolve(options.packageName().replace('.', '/'));
    }

    private static Path nativeMetadata(CodegenOptions options) {
        return options.resourceOutput()
            .resolve("META-INF/native-image")
            .resolve("io.github.absketches")
            .resolve("runway")
            .resolve(options.packageName() + "." + options.className())
            .resolve("reachability-metadata.json");
    }
}
