package io.github.absketches.runway.codegen;

import io.github.absketches.runway.codegen.sql.CodegenDialect;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RunwayGeneratorTest {
    private static final String PACKAGE_NAME = "io.github.absketches.runway.generated";
    private static final String CLASS_NAME = "GeneratedRunwayMigrations";

    @TempDir
    Path tempDir;

    @Test
    void generatesCompilableRegistry() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (name text default '\"\"\"');\r\n");
        Files.writeString(
            input.resolve("V2__create_user_view.sql"),
            "create view user_view as select name from users;\n"
        );

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        Path packageDirectory = packageDirectory(options);
        String catalog = Files.readString(packageDirectory.resolve(CLASS_NAME + ".java"));
        assertTrue(catalog.startsWith("// Generated by Runway. Do not edit."));
        assertTrue(catalog.contains("Migrations.builder(\"SQLite\")"));
        assertTrue(catalog.contains("V1_CreateUsers.register(builder)"));
        assertTrue(catalog.contains("V2_CreateUserView.register(builder)"));

        String migration = Files.readString(packageDirectory.resolve("V1_CreateUsers.java"));
        assertTrue(migration.startsWith("// Generated by Runway. Do not edit."));
        assertTrue(migration.contains("sha256:"));
        assertTrue(migration.contains("builder.versioned("));
        assertTrue(migration.contains("List.of("));
        assertTrue(migration.contains("statement-000.sql"));
        assertTrue(!migration.contains("SqlImpact"));
        assertTrue(!migration.contains("create table users"));

        Path statement = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/V1__create_users/statement-000.sql"
        );
        assertEquals("create table users (name text default '\"\"\"');\n", Files.readString(statement));

        String nativeMetadata = Files.readString(nativeMetadata(options));
        assertTrue(nativeMetadata.contains("\"typeReached\": \"" + PACKAGE_NAME + "." + CLASS_NAME + "\""));
        assertTrue(nativeMetadata.contains("\"glob\": \"io/github/absketches/runway/generated/runway/**\""));

        assertTrue(migration.contains("import io.github.absketches.runway.Migrations;"));
    }

    @Test
    void rejectsDuplicateVersions() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__first.sql"), "select 1;\n");
        Files.writeString(input.resolve("V1__second.sql"), "select 2;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));
        assertTrue(exception.getMessage().contains("Duplicate versioned migration version"));
    }

    @Test
    void rejectsProceduresAndFunctions() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);

        for (String sql : List.of(
            "create procedure demo() begin select 1; end;",
            "create function demo() returns integer return 1;",
            "create or replace function demo() returns integer return 1;",
            "create definer = 'app'@'localhost' procedure demo() select 1"
        )) {
            Files.writeString(input.resolve("V1__unsupported.sql"), sql);
            CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
                options(input, null)
            ));
            assertTrue(exception.getMessage().contains("does not currently support"));
        }
    }

    @Test
    void acceptsStatementsOutsideImpactAnalyzerCoverage() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__operations.sql"), """
            select * from users;
            truncate table audit_log;
            grant select on users to reporting;
            """);

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        Path resourceDirectory = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/V1__operations"
        );
        assertTrue(Files.exists(resourceDirectory.resolve("statement-000.sql")));
        assertTrue(Files.exists(resourceDirectory.resolve("statement-001.sql")));
        assertTrue(Files.exists(resourceDirectory.resolve("statement-002.sql")));
    }

    @Test
    void readsAndWritesSqlAsUtf8() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        String sql = "insert into messages (content) values ('Grüße');\n";
        Files.writeString(input.resolve("V1__message.sql"), sql, StandardCharsets.UTF_8);
        Path impactReport = tempDir.resolve("impact.html");

        CodegenOptions options = options(input, impactReport);
        new RunwayGenerator().generate(options);

        Path statement = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/V1__message/statement-000.sql"
        );
        assertEquals(sql, Files.readString(statement, StandardCharsets.UTF_8));
        String report = Files.readString(impactReport);
        assertTrue(report.contains("<!doctype html>"));
        assertTrue(report.contains("<input id=\"search\""));
        assertTrue(report.contains("<button id=\"clear-selection\" type=\"button\" disabled>Clear selection</button>"));
        assertTrue(report.contains("row.classList.toggle(\"selected\")"));
        assertTrue(report.contains("messages (table)"));
        assertTrue(report.contains("columns"));
        assertTrue(report.contains("data-column-search=\"messages (table) columns content messages.content\""));
        assertTrue(report.contains(">content</th>"));
        assertTrue(report.contains("<tr data-file-row data-file=\"V1__message.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("<span class=\"marker data\">D</span>"));
        assertTrue(report.contains("<td class=\"number\">0</td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"merge-target\"></td><td class=\"data-change\">data changes</td>"));
    }

    @Test
    void impactReportShowsResourceGridAndConsolidationStatus() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__update_users.sql"), """
            update users u
            set status = r.default_status
            from roles r
            where u.role_id = r.id;
            """);
        Files.writeString(input.resolve("V2__rewrite_status.sql"), """
            update users
            set status = 'active';
            """);
        Files.writeString(input.resolve("V3__index_users_status.sql"), """
            create index users_status_idx
            on users (status);
            """);
        Files.writeString(input.resolve("V4__create_user_names_legacy.sql"), """
            create view user_names as
            select id
            from users;
            """);
        Files.writeString(input.resolve("V5__create_reporting_views.sql"), """
            create view user_ids as
            select id
            from users;

            create view role_names as
            select id
            from roles;
            """);
        Files.writeString(input.resolve("V6__replace_user_names.sql"), """
            drop view if exists user_names;

            create view user_names as
            select id, status
            from users;
            """);
        Files.writeString(input.resolve("V7__replace_user_ids.sql"), """
            drop view if exists user_ids;

            create view user_ids as
            select id, status
            from users;
            """);
        Files.writeString(input.resolve("V8__data_change_with_unknown.sql"), """
            update users
            set status = 'active';

            grant select on users to reporting;
            """);
        Path impactReport = tempDir.resolve("impact.html");

        new RunwayGenerator().generate(options(input, impactReport));

        String report = Files.readString(impactReport);
        assertTrue(report.contains("<h2>Table and Object Matrix</h2>"));
        assertTrue(report.contains("users (table)"));
        assertTrue(report.contains("roles (table)"));
        assertTrue(report.contains("database objects"));
        assertTrue(report.contains(">indexes</th>"));
        assertTrue(report.indexOf(">database objects</th>") > report.indexOf(">roles (table)</th>"));
        assertTrue(report.contains(">users_status_idx</th>"));
        assertTrue(!report.contains("<th>(table)</th>"));
        assertTrue(report.contains("<tr data-file-row data-file=\"V3__index_users_status.sql\" data-status=\"active\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V2__rewrite_status.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V1__update_users.sql\" data-status=\"data changes\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V8__data_change_with_unknown.sql\" data-status=\"incomplete analysis\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V5__create_reporting_views.sql\" data-status=\"partial merge candidate\""));
        assertTrue(report.contains("<tr data-file-row data-file=\"V4__create_user_names_legacy.sql\" data-status=\"merge candidate\""));
        assertTrue(report.contains("title=\"Superseded by V6__replace_user_names.sql\">w</span>"));
        assertTrue(report.contains("<h2>Consolidation Candidates</h2>"));
        assertTrue(report.contains("<td><code>V3__index_users_status.sql</code></td><td class=\"number\">1</td><td class=\"number\">1</td><td class=\"number\">0</td><td class=\"merge-target\"></td><td class=\"active\">active</td>"));
        assertTrue(report.contains("<td><code>V2__rewrite_status.sql</code></td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"merge-target\"></td><td class=\"data-change\">data changes</td>"));
        assertTrue(report.contains("<td><code>V1__update_users.sql</code></td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"merge-target\"></td><td class=\"data-change\">data changes</td>"));
        assertTrue(report.contains("<td><code>V8__data_change_with_unknown.sql</code></td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"number\">0</td><td class=\"merge-target\"></td><td class=\"incomplete\">incomplete analysis</td>"));
        assertTrue(report.contains("<td><code>V5__create_reporting_views.sql</code></td><td class=\"number\">2</td><td class=\"number\">1</td><td class=\"number\">1</td><td class=\"merge-target\"><div><code>V7__replace_user_ids.sql</code><span class=\"points\">views.user_ids</span></div></td><td class=\"partial\">partial merge candidate</td>"));
        assertTrue(report.contains("<td><code>V4__create_user_names_legacy.sql</code></td><td class=\"number\">1</td><td class=\"number\">0</td><td class=\"number\">1</td><td class=\"merge-target\"><div><code>V6__replace_user_names.sql</code><span class=\"points\">views.user_names</span></div></td><td class=\"merge\">merge candidate</td>"));
    }

    @Test
    void doesNotRejectUnsupportedKeywordsInsideCommentsOrStrings() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__keywords.sql"), """
            -- create function is documentation here
            insert into messages (content) values ('create trigger is plain text');
            """);

        CodegenOptions options = options(input, null);
        new RunwayGenerator().generate(options);

        assertTrue(Files.exists(options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/V1__keywords/statement-000.sql"
        )));
    }

    @Test
    void preservesOtherNativeImageMetadata() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");

        CodegenOptions options = options(input, null);
        Path existing = options.resourceOutput()
            .resolve("META-INF/native-image/example/other/reachability-metadata.json");
        Path existingPackageMetadata = options.resourceOutput()
            .resolve("META-INF/native-image")
            .resolve(PACKAGE_NAME.replace('.', '/'))
            .resolve(CLASS_NAME)
            .resolve("reachability-metadata.json");
        Files.createDirectories(existing.getParent());
        Files.createDirectories(existingPackageMetadata.getParent());
        Files.writeString(existing, "{\"reflection\":[]}\n");
        Files.writeString(existingPackageMetadata, "{\"resources\":[]}\n");

        new RunwayGenerator().generate(options);

        assertEquals("{\"reflection\":[]}\n", Files.readString(existing));
        assertEquals("{\"resources\":[]}\n", Files.readString(existingPackageMetadata));
        assertTrue(Files.exists(nativeMetadata(options)));
    }

    @Test
    void removesStaleGeneratedMigrationOutput() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Path obsolete = input.resolve("V2__obsolete.sql");
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");
        Files.writeString(obsolete, "create table obsolete (id integer);\n");

        CodegenOptions options = options(input, null);
        Path handwritten = packageDirectory(options).resolve("HandWritten.java");
        Files.createDirectories(handwritten.getParent());
        Files.writeString(handwritten, """
            package io.github.absketches.runway.generated;

            final class HandWritten {
            }
            """);
        new RunwayGenerator().generate(options);
        Path obsoleteSource = packageDirectory(options).resolve("V2_Obsolete.java");
        Path obsoleteResource = options.resourceOutput().resolve(
            "io/github/absketches/runway/generated/runway/V2__obsolete/statement-000.sql"
        );
        assertTrue(Files.exists(obsoleteSource));
        assertTrue(Files.exists(obsoleteResource));

        Files.delete(obsolete);
        new RunwayGenerator().generate(options);

        assertTrue(Files.notExists(obsoleteSource));
        assertTrue(Files.notExists(obsoleteResource));
        assertTrue(Files.exists(handwritten));
    }

    @Test
    void refusesToOverwriteNonRunwayJavaSource() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1__create_users.sql"), "create table users (id integer);\n");

        CodegenOptions options = options(input, null);
        Path catalog = packageDirectory(options).resolve(CLASS_NAME + ".java");
        Files.createDirectories(catalog.getParent());
        Files.writeString(catalog, """
            package io.github.absketches.runway.generated;

            final class GeneratedRunwayMigrations {
            }
            """);

        CodegenException exception = assertThrows(
            CodegenException.class,
            () -> new RunwayGenerator().generate(options)
        );

        assertTrue(exception.getMessage().contains("Refusing to overwrite non-Runway Java source"));
    }

    @Test
    void rejectsGeneratedClassNameCollisions() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("V1-1__create-users.sql"), "create view users_a as select id from users;\n");
        Files.writeString(input.resolve("V1_1__create users.sql"), "create view users_b as select id from users;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));

        assertTrue(exception.getMessage().contains("same Java class"));
    }

    @Test
    void rejectsRepeatableMigrationFilenames() throws Exception {
        Path input = tempDir.resolve("runway");
        Files.createDirectories(input);
        Files.writeString(input.resolve("R__refresh_users.sql"), "create view users_v as select id from users;\n");

        CodegenException exception = assertThrows(CodegenException.class, () -> new RunwayGenerator().generate(
            options(input, null)
        ));

        assertTrue(exception.getMessage().contains("Invalid migration filename"));
    }

    private CodegenOptions options(Path input, Path impactReport) {
        return new CodegenOptions(
            input,
            tempDir.resolve("sources"),
            tempDir.resolve("resources"),
            PACKAGE_NAME,
            CLASS_NAME,
            CodegenDialect.SQLITE,
            impactReport
        );
    }

    private static Path packageDirectory(CodegenOptions options) {
        return options.sourceOutput().resolve(options.packageName().replace('.', '/'));
    }

    private static Path nativeMetadata(CodegenOptions options) {
        return options.resourceOutput()
            .resolve("META-INF/native-image")
            .resolve("io.github.absketches")
            .resolve("runway")
            .resolve(options.packageName() + "." + options.className())
            .resolve("reachability-metadata.json");
    }
}
