package io.github.absketches.runway.codegen.output;

import io.github.absketches.runway.codegen.migration.ParsedMigration;
import io.github.absketches.runway.codegen.migration.ParsedStatement;

import java.util.List;

public final class JavaSourceWriter {
    private static final String GENERATED_MARKER = "// Generated by Runway. Do not edit.";
    private static final String ENTRY_INDENT = "        ";
    private static final String ARGUMENT_INDENT = "            ";

    private JavaSourceWriter() {
    }

    public static String generatedMarker() {
        return GENERATED_MARKER;
    }

    public static String catalogMarker(String packageName, String className) {
        return "// Runway catalog: " + packageName + "." + className;
    }

    public static String writeCatalog(
        String packageName,
        String className,
        String dialectName,
        String codegenVersion,
        List<ParsedMigration> migrations
    ) {
        StringBuilder registrations = new StringBuilder();
        for (ParsedMigration migration : migrations) {
            registrations.append("        ")
                .append(migrationClassName(migration))
                .append(".register(builder);\n");
        }

        return """
            %s
            %s
            package %s;

            import io.github.absketches.runway.MigrationRegistry;
            import io.github.absketches.runway.Migrations;

            public final class %s {
                private %s() {
                }

                public static MigrationRegistry registry() {
                    Migrations.Builder builder = Migrations.builder(%s, %s);
            %s        return builder.build();
                }
            }
            """.formatted(
            GENERATED_MARKER,
            catalogMarker(packageName, className),
            packageName,
            className,
            className,
            quote(dialectName),
            quote(codegenVersion),
            registrations
        );
    }

    public static String writeMigration(String packageName, String catalogClassName, ParsedMigration migration) {
        String className = migrationClassName(migration);
        return """
            %s
            %s
            package %s;

            import io.github.absketches.runway.Migrations;

            import java.io.InputStream;
            import java.util.List;

            final class %s {
                private %s() {
                }

                static void register(Migrations.Builder builder) {
            %s    }

                private static InputStream openResource(String resourcePath) {
                    return %s.class.getResourceAsStream(resourcePath);
                }
            }
            """.formatted(
            GENERATED_MARKER,
            catalogMarker(packageName, catalogClassName),
            packageName,
            className,
            className,
            entry(className, migration),
            className
        );
    }

    public static String migrationClassName(ParsedMigration migration) {
        String prefix = "V" + migration.version().replaceAll("[^A-Za-z0-9]", "_");
        StringBuilder name = new StringBuilder(prefix).append('_');
        for (String word : migration.description().split("[^A-Za-z0-9]+")) {
            if (!word.isEmpty()) {
                name.append(Character.toUpperCase(word.charAt(0)))
                    .append(word.substring(1));
            }
        }
        return name.toString();
    }

    private static String entry(String className, ParsedMigration migration) {
        return entry(
            "versioned",
            quote(migration.version()),
            quote(migration.description()),
            quote(migration.path().getFileName().toString()),
            quote(migration.checksum()),
            className + "::openResource",
            statements(migration)
        );
    }

    private static String statements(ParsedMigration migration) {
        StringBuilder source = new StringBuilder("List.of(\n");
        for (int i = 0; i < migration.statements().size(); i++) {
            source.append(statement(migration.statements().get(i)));
            if (i < migration.statements().size() - 1) {
                source.append(",");
            }
            source.append("\n");
        }
        return source.append(ARGUMENT_INDENT).append(")").toString();
    }

    private static String statement(ParsedStatement statement) {
        return ARGUMENT_INDENT + "    " + quote(statement.resourcePath());
    }

    private static String entry(String builderMethod, String... arguments) {
        return ENTRY_INDENT + "builder." + builderMethod + "(\n"
            + arguments(arguments)
            + ENTRY_INDENT + ");\n";
    }

    private static String arguments(String... arguments) {
        StringBuilder source = new StringBuilder();
        for (int i = 0; i < arguments.length; i++) {
            source.append(ARGUMENT_INDENT).append(arguments[i]);
            if (i < arguments.length - 1) {
                source.append(",");
            }
            source.append("\n");
        }
        return source.toString();
    }

    private static String quote(String value) {
        return "\"" + value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t") + "\"";
    }
}
